In [ ]:
import numpy as np
import numpy.matlib as mt

from ephysvibe.structures.neuron_data import NeuronData

In [1]:
import pandas as pd

In [4]:
data=pd.read_csv("C:/Users/camil/Documents/pfc_neurons_info.csv")

In [ ]:
data[['x_pos_sample','y_pos_sample']].groupby(['x_pos_sample','y_pos_sample']).count()

Empty DataFrame
Columns: []
Index: [(3.0, -5.0), (4.0, -5.0), (4.0, -4.0), (5.0, -5.0), (6.0, -2.0), (7.0, -7.0), (7.0, -5.0), (7.0, -2.0), (7.0, 0.0), (7.0, 7.0), (8.0, 5.0), (10.0, 0.0), (11.0, 0.0)]

: 

In [2]:
pp=NeuronData.from_python_hdf5("//envau_cifs.intlocal.univ-amu.fr/work/invibe/USERS/IBOS/data/Riesling/TSCM/OpenEphys/new_structure/session_struct/lip/neurons/2022-11-30_10-42-03_Riesling_lip_e1_r1_mua2_neu.h5")

In [6]:
pp.position[np.logical_and(pp.block==1,pp.pos_code==-1)]

array([[[-5.,  5.],
        [ 5., -5.]],

       [[-5.,  5.],
        [ 5., -5.]],

       [[-5.,  5.],
        [ 5., -5.]],

       ...,

       [[-5.,  5.],
        [ 5., -5.]],

       [[-5.,  5.],
        [ 5., -5.]],

       [[-5.,  5.],
        [ 5., -5.]]])

In [5]:
pp.position[np.logical_and(pp.block==1,pp.pos_code==1)]

array([[[ 5., -5.],
        [-5.,  5.]],

       [[ 5., -5.],
        [-5.,  5.]],

       [[ 5., -5.],
        [-5.,  5.]],

       ...,

       [[ 5., -5.],
        [-5.,  5.]],

       [[ 5., -5.],
        [-5.,  5.]],

       [[ 5., -5.],
        [-5.,  5.]]])

In [7]:
mask_in = np.logical_and(pp.block==1,pp.pos_code==1)
position = pp.position[mask_in]
u_pos = np.unique(position, axis=0)

if u_pos.shape[0] > 1:
    x_pos, y_pos = np.nan, np.nan
else:
    x_pos, y_pos = u_pos[0][0][0], u_pos[0][0][1]

In [8]:
u_pos

array([[[ 5., -5.],
        [-5.,  5.]]])